# Generated by Django 4.1.5 on 2023-03-04 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("habitrackapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="user",
        ),
        migrations.AddField(
            model_name="template",
            name="user",
            field=models.ManyToManyField(
                blank=True, related_name="templates", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
