# Generated by Django 4.1.5 on 2023-03-04 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("habitrackapp", "0002_remove_template_user_template_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
