# Generated by Django 4.1.7 on 2023-03-07 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habitrackapp", "0003_template_creator"),
    ]

    operations = [
        migrations.RenameField(
            model_name="template",
            old_name="user",
            new_name="subscribers",
        ),
    ]
